### ISSUE TITLE
02-reflection CSS/styling should be more accurate

### ISSUE THREAD

**Issue by dantaeyoung** [lmccart/the-changing-room#54]

**Comment by dantaeyoung** [comment]
This includes: 
- [ ] Sizing to actual width / size of projected screen (actual info here: https://drive.google.com/file/d/1-v3aUaMVW5qqyX1UN9OA7wA88xnZKhU_/view)
- [ ] Better sizing of memory windows and positions
- [ ] More accurate color 
- [ ] Using different background images

**Comment by lmccart** [comment]
**re: background images**
this is drawing from the same image base, but using some css to arrange them onscreen. see image here: https://github.com/lmccart/the-changing-room/issues/31#issue-765564551. it will take a bit of math.

the middle screen should have the image centered, there may be some overflow on left/right if it's a 1920x1080 image, or on top/bottom if it's a square image.

the left and right screens should use the same image, but mirrored. then it should be cropped/placed so that the edge that meets the middle screen looks like it aligns.

does that make sense?

**re: sizing**
can you make sure the screen dimensions are variables in the code so this can be easily adjusted onsite if needed?
and that sizing is done in terms of `vw/vh` as much as possible.

**Comment by dantaeyoung** [comment]
That makes sense re:sizing & centering & mirroring, and will pull those out as variables and size with `vw/vh`. Thanks for clarifying.

**Comment by lmccart** [comment]
Also responding to this question from the log: "Exact timing for 02-reflection - should the images be randomly interspersed with the text?"
I think this refers to the memories part. Images and/or text should be randomly paired (image-image or image-text) and pop up together. See [this image](https://user-images.githubusercontent.com/191056/102019482-b172a980-3d28-11eb-803a-f5379a53f688.png) for reference. Size of image could vary.

Time permitting: Could we try having a couple different cropping divs around the images? It would be nice to have some vertical images, in addition to the 16:9 and 1:1 aspect ratios.

**Comment by dantaeyoung** [comment]
Hi @lmccart - I'm closing this and breaking this issue out into #94, #97, #98, #99 so it's easier to keep track. Let me know if there's anything I'm missing.
