### ISSUE TITLE
Faces to be tested and fullscreen on Safari (SSL certificate may be needed)

### ISSUE THREAD

**Issue by melaniehoff** [lmccart/the-changing-room#92]
A few snags appeared when displaying faces on an ipad with safari, one of them is that it looks like to use webcam video on safari with an ip address (not localhost) an SSL cert is needed @lmccart

**Comment by lmccart** [comment]
Ah, I see, thank you for looking into this. Have you gotten this to work with chrome? I'm not able to get the camera feed going there either. Could it be the same issue?

**Comment by lmccart** [comment]
Update: I was able to get this working my making an SSL certificate. There's a nice tool that does most it for you here: https://github.com/FiloSottile/mkcert

Now I can get camera working on Safari, but not on Chrome. I'm currently updating ipad software, and I also have a pretty old model, so I'm curious whether it works for you in either browser?

On Safari, I can get it to load in the browser, but when I try the "Add to Home Screen" button, it doesn't work. It seems related to [this bug](https://stackoverflow.com/questions/46228218/how-to-access-camera-on-ios11-home-screen-web-app), but I can't tell if it's been completely fixed since then or not. I don't see many comments recently, so it makes me hopeful this does work on newer ipads.

**Comment by lmccart** [comment]
Ok great news, after updating my ipad software, webcam works in fullscreen mode on ipad safari. From what I've read, getusermedia doesn't work on chrome at all, so I think we want to stick with safari. Unless you've found differently? I'll push my changes to a branch shortly.

**Comment by melaniehoff** [comment]
ohh that's great news!
